name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Necessary for complete history

    - name: Configure user information
      run: |
        git config user.name "maxregnerklos"
        git config user.email "plodmrasif@gmail.com"

    - name: Add upstream repository
      run: git remote add upstream https://github.com/WOA-Project/WOA-Deployer.git

    - name: Fetch changes from upstream
      run: git fetch upstream

    - name: Checkout main branch
      run: git checkout master  # Adjust according to your branch name, e.g., main

    - name: Merge upstream changes favoring their changes
      run: |
        # Automatically favoring their changes during conflicts
        # Adding --allow-unrelated-histories to deal with different commit histories
        git merge upstream/master --allow-unrelated-histories -X theirs
      shell: /usr/bin/bash -e {0}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master  # Adjust according to your branch name, e.g., main
